source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll", ">= 3.6.3"
  gem "ffi", ">= 1.9.24"
  gem "jekyll-sitemap", "~> 1.2.0"
  gem "jemoji", "~> 0.10.1"
  gem "jekyll-feed", "~> 0.11.0"
  gem "kramdown-parser-gfm"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

