# Site settings
title: "rishi raj's blog"
description: >
  On marketing, tech, and building a services co.

author: Rishi Raj
email: r@rishi.im
username: Rishi Raj

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rishiraj.blog" # the base hostname & protocol for your site

github_edit_url: "https://github.com/sobolevn/sobolevn.github.io/blob/master"
disqus_id: 
google_analytics_id: UA-

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:title
future: false

# Performance settings
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []

collections:
  talks:
    output: true
    permalink: /:collection/:name
  activities:
    output: true
    permalink: /:collection/:name

feed:
  collections:
    - talks
    - activities

sass:
  style: compressed

exclude: [vendor]

# Plugins:
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
