# Site settings
title: "rishi raj's blog"
description: >
  On work, and building a services co.
  Also, rants about tech and management.

author: Rishi Raj
email: r@rishi.im
username: imrishi

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rishiraj.blog" # the base hostname & protocol for your site

github_edit_url: "https://github.com/sobolevn/sobolevn.github.io/blob/master"
disqus_id: 
google_analytics_id: UA-

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:title

collections:
  talks:
    output: true
    permalink: /:collection/:name
  activities:
    output: true
    permalink: /:collection:/:name

feed:
  collections:
    - talks
    - activities

sass:
  style: compressed

exclude: [vendor]

# Plugins:
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
